app_path = "/home/pi/beemo"
database_path = "/home/pi/beemo/data/data.json"
wav_path = "/home/pi/beemo/data/wav"
fft_path = "/home/pi/beemo/data/fft"
error_log = "/home/pi/beemo/error.log"
info_log = "/home/pi/beemo/info.log"
config_path = "/home/pi/conf.ini"
data_dir_path = "/home/pi/beemo/data/"
